src/Entity/Trick.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrickRepository")
 */
class Trick
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image",cascade={"persist", "remove", "refresh"}, mappedBy="trick")
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment",cascade={"persist", "remove", "refresh"}, mappedBy="trick")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Video",cascade={"persist", "remove", "refresh"}, mappedBy="trick")
     */
    private $videos;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="tricks")
     */
    private $categories;

    public function __construct()
    {
        $this->created = new \DateTime();
        $this->images = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->category = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(?\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setTrick($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getTrick() === $this) {
                $image->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @param Category $category
     */
    public function addCategory(Category $category)
    {
        $this->categories[] = $category;
    }

    /**
     * @param Category $category
     */
    public function removeCategory(Category $category)
    {
        $this->categories->removeElement($category);
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): ?Collection
    {
        return $this->categories;
    }
    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->contains($video)) {
            $this->videos->removeElement($video);
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }
    /**
     * @return string
     */
    public function getTrickImage(): string
    {
        $path = '/images/jumb.jpg';

        if(!$this->images->isEmpty()) {
            $image = $this->images->first();
            $path = $image->getPath();
        }

        return $path;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Table(name="app_users")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $email;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="json_array", nullable=true)
     */
    private $roles;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $confirmToken;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resetToken;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="user")
     */
    private $comments;
    /**
     * @var string
     */
    private $plainPassword;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Avatar", cascade={"persist", "remove","refresh"})
     */
    private $avatar;


    public function __construct()
    {
        $this->isActive = true;
        $this->comments = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    public function setRoles($roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getConfirmToken(): ?string
    {
        return $this->confirmToken;
    }

    public function setConfirmToken(?string $confirmToken): self
    {
        $this->confirmToken = $confirmToken;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    public function getSalt()
    {
        return null;
    }


    public function eraseCredentials()
    {
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,

        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,

            ) = unserialize($serialized);
    }

    /**
     * @return Avatar
     */
    public function getAvatar(): ?Avatar
    {
        return $this->avatar;
    }

    /**
     * @param Avatar $avatar
     * @return $this
     */
    public function setAvatar(Avatar $avatar)
    {
        $this->avatar = $avatar;

        return $this;
    }
    /**
     * @return string
     */
    public function getAvatarPath(): ?string
    {
        $path = '/images/avatar.jpg';

        if(!is_null($this->avatar))
            $path = $this->avatar->getPath();

        return $path;
    }

}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Trick;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 			TextType::class)
            ->add('description', 	TextareaType::class)
            ->add('categories', 	EntityType::class, array(
                'class'			=>	'App\Entity\Category',
                'choice_label'	=>	'name',
                'multiple'		=>	true
            ))
            ->add('images',			CollectionType::class, array(
                'entry_type'	=>	ImageType::class,
                'allow_add'		=>	true,
                'allow_delete'	=>	true,
                'by_reference'	=> 	false
            ))
            ->add('videos', 		CollectionType::class, array(
                'entry_type'	=>	VideoType::class,
                'allow_add'		=> 	true,
                'allow_delete'	=> 	true,
                'by_reference'	=> 	false
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
            'csrf_protection' => true
        ]);
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Trick;
use App\Form\CommentType;
use App\Form\TrickType;
use App\Repository\TrickRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 *
 */
class TrickController extends Controller
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    /**
     * HomeController constructor.
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/", name="home", methods="GET")
     */
    public function index(TrickRepository $trickRepository): Response
    {
        return $this->render('trick/index.html.twig', [
            'tricks' => $trickRepository->findAll()
        ]);
    }

    /**
     * @Route("/new", name="trick_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $trick = new Trick();
        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->entityManager->persist($trick);
            $this->entityManager->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('trick/new.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/trick/show/{id}", name="trick_show", methods="GET|POST")
     */
    public function show(Trick $trick, Request $request): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment)
            ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($comment);

            $comment->setUser($this->getUser());
            $comment->setTrick($trick);


            $this->entityManager->flush();

            $this->addFlash('success', 'Votre commentaire est ajouté !');

            return $this->redirectToRoute('trick_show', [
                'id' => $trick->getId()
            ]);

        }
        return $this->render('trick/show.html.twig', [
            'form' => $form->createView(),
            'trick' => $trick
        ]);
    }

    /**
     * @Route("trick/edit/{id}", name="trick_edit", methods="GET|POST")
     */
    public function edit(Request $request, Trick $trick): Response
    {

        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->entityManager->flush();

            return $this->redirectToRoute('trick_edit', ['id' => $trick->getId()]);
        }

        return $this->render('trick/edit.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("delete/{id}", name="trick_delete", methods="DELETE")
     */
    public function delete(Request $request, Trick $trick): Response
    {
        if ($this->isCsrfTokenValid('delete'.$trick->getId(), $request->request->get('_token'))) {

            $this->entityManager->remove($trick);
            $this->entityManager->flush();

            $this->addFlash('success', "la figure est supprimée.");

            return $this->redirectToRoute('home');
        }
    }
}

templates/trick/_delete_form.html.twig
<form method="post" action="{{ path('trick_delete', {'id': trick.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id) }}">
    <button class="btn">Delete</button>
</form>

templates/trick/edit.html.twig
{% extends "base.html.twig" %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('/css/trick.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/trick-edit.css') }}">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('/js/app.js') }}"></script>
    <script src="{{ asset('/js/trick-edit.js') }}"></script>
{% endblock %}

{% block modals %}
    {{ parent() }}
    {{ include('form/_delete_trick_confirmation.html.twig') }}
{% endblock %}

{% block body %}
    <section id="cover" class="cover d-none d-sm-block">
    </section>

    <section class="trick-content mb-3 mb-sm-5 pt-3 pt-sm-5">
        <div class="container">
            <div class="trick pb-4 px-2">
                {{ include('form/_edit_trick_form.html.twig') }}
            </div>
        </div>
    </section>

{% endblock %}

templates/trick/index.html.twig
{% extends 'base.html.twig' %}


{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('/css/home.css') }}">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('/js/app.js') }}"></script>
{% endblock %}

{% block modals %}
    {{ parent() }}
{% endblock %}

{% block body %}
    <section id="cover" class="cover">
        <div class="cover-inner">
            <div class="cover-catch">
            <b>Bienvenue sur SnowTricks,</b><br>
            <b>Le site des amateurs de snowboard.</b><br>
            <b>Des informations sur les tricks, Des figures.. </b><br>

        </div>
        <div class="cover-goto">
            <a href="#trick_list">
                <i class="fas fa-arrow-alt-circle-down"></i>
            </a>
        </div>
        </div>
    </section>

    <section id="trick_list">
        <div class="container-fluid">
            <div class="trick-list">
                <div class="row">
                    {% for trick in tricks %}
                        <div class="col-xl-3 col-lg-4 col-md-6 col-xs-12 {% if loop.index >= 5 %}hidden-trick{% endif %}">
                            <div class="trick-item">
                                <div class="trick-image">
                                    <div class="embed-responsive embed-responsive-16by9">
                                        <a class="embed-responsive-item" href="{{ path('trick_show', {'id': trick.id}) }}">
                                            <img src="{{ asset(trick.trickImage) }}">
                                        </a>
                                    </div>
                                </div>
                                <div class="trick-name">
                                    <ul class="flex-row">
                                        <li class="name">
                                            <a href="{{ path('trick_show', {'id': trick.id}) }}">
                                                {{ trick.name }}
                                            </a>
                                        </li>
                                        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                            <li class="action edit">
                                                <a href="{{ path('trick_edit',{'id':trick.id }) }}">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                            </li>
                                            <li class="action delete">
                                              {{ include('trick/_delete_form.html.twig') }}

                                            </li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="text-center">
                </div>

                {% if tricks|length > 5 %}
                    <div class="text-center">
                        <button class="btn btn-info mr-3"
                                onclick="this.remove(); $('.hidden-trick').show(); $('.trick-goto a').show();">Voir plus
                        </button>
                        <a href="" class="btn btn-dark">Ajouter un trick</a>
                    </div>
                    <div class="trick-goto text-right">
                        <a href="#top">
                            <i class="fas fa-arrow-alt-circle-up"></i>
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

templates/trick/new.html.twig
{% extends "base.html.twig" %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('/css/trick.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/trick-edit.css') }}">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('/js/app.js') }}"></script>
    <script src="{{ asset('/js/trick-edit.js') }}"></script>
{% endblock %}

{% block body %}
    <section id="cover" class="cover d-none d-sm-block">
    </section>



    <section class="trick-content mb-3 mb-sm-5 pt-3 pt-sm-5">
        <div class="container">
            <div class="trick pb-4 px-2">
                {{ include('form/_create_trick_form.html.twig') }}
            </div>
        </div>
    </section>

{% endblock %}

templates/trick/show.html.twig
{% extends "base.html.twig" %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('/css/trick.css') }}">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('/js/app.js') }}"></script>
{% endblock %}

{% block modals %}
    {{ parent() }}
    {{ include('Form/_delete_trick_confirmation.html.twig') }}
{% endblock %}

{% block body %}
    <section id="cover" class="cover d-none d-sm-block">
    </section>



    <section class="trick-content mb-3 mb-sm-5 pt-3 pt-sm-5">
        <div class="container">
            <div class="trick-thumbnail" style="background-image: url({{ asset(trick.trickImage) }})">
                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <div class="trick-action">
                        <div class="action-edit text-center">
                            <a href="{{ path('trick_edit', {'id': trick.id}) }}">
                                <i class="fas fa-edit"></i>
                            </a>
                        </div>
                        <div class="action-delete text-center">
                            {{ include('form/_delete_trick_form.html.twig', {trick: trick}) }}
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="trick pb-4">
                <div class="trick-name text-left text-sm-center">
                    <span>{{ trick.name }}</span>
                </div>
                {% if not trick.images.empty %}
                    <div class="d-block d-sm-none text-center">
                        <button class="btn btn-info mt-4" onclick="this.remove(); $('.trick-media').removeClass('d-none');">Voir les médias</button>
                    </div>
                {% endif %}
                <div class="trick-media px-4 d-none d-sm-block">
                    <div class="row justify-content-center">
                        {% if not trick.images.empty %}
                            {% for image in trick.images %}
                                <div class="col-xl-4 col-lg-6 col-md-6 px-3">
                                    <div class="embed-responsive embed-responsive-16by9 media-image mt-4 mt-4" style="background-image: url({{ asset(image.path) }});">
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}

                        {% if not trick.videos.empty %}
                            {% for video in trick.videos %}
                                <div class="col-xl-4 col-lg-6 col-md-6 px-3">
                                    <div class="embed-responsive embed-responsive-16by9 mt-4">
                                        <iframe class="embed-responsive-item" src="{{ video.iframe }}" allowfullscreen></iframe>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>

                <div class="trick-description pt-4 px-4">
                    <p class="text-justify">
                        {{ trick.description }}
                    </p>
                </div>

                <div class="trick-informations">
                    <ul class="list-unstyled m-0 d-flex justify-content-center">
                        <li class="mx-2">
                            Ajouté le : {{ trick.created|date("d/m/Y") }}
                        </li>
                        {% if trick.created != trick.updated %}
                            <li class="mx-2">
                                Dernière édition : {{ trick.updated|date("d/m/Y") }}
                            </li>
                        {% endif %}
                        <li class="mx-2">
                                Catégories :
                                {% for category in trick.categories %}
                                    {{ category.name }}
                                {% endfor %}
                        </li>
                    </ul>
                </div>

                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <div class="trick-comment-form py-4 mx-4 mt-4">
                        <div class="row justify-content-center">
                            <div class="col-xl-7">
                                {{ include('form/_add_comment_form.html.twig') }}
                            </div>
                        </div>
                    </div>
                {% endif %}

                {% if not trick.comments.empty %}
                    <div class="trick-comments px-4">
                        <div class="row justify-content-center">
                            <div class="col-xl-7">
                                <ul class="list-unstyled m-0">
                                    {% for comment in trick.comments %}
                                        <li class="comment-item media mt-4 {% if loop.index >= 6 %}hidden-comment{% endif %}">
                                            <img class="mr-3 rounded" src="{{ asset(comment.user.avatarPath) }}">
                                            <div class="media-body">
                                                <h5 class="mt-0 mb-1">{{ comment.user.username }} <small>{{ comment.date|date('Y-m-d H:i:s') }}</small></h5>
                                                {{ comment.content }}
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>

                        {% if trick.comments|length > 5 %}
                            <div class="text-center">
                                <button class="btn btn-info mt-4" onclick="this.remove(); $('.hidden-comment').css('display', 'flex');">Voir plus</button>
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}